use crate::api_key::validate_api_key_format;
use crate::cli::ImageSource;
use crate::clipboard::{convert_image_data_to_base64, read_clipboard_image};
use crate::constants::GEMINI_API_KEY_URL;
use crate::logging::{log_debug, log_error, log_info, log_warn};
use crate::provider::AiProvider;
use crate::tools::{FunctionCall, WebTools};
use anyhow::{Context, Result};
use async_trait::async_trait;
use genai::chat::{ChatMessage, ChatRequest, ContentPart};
use genai::Client;
use rand::prelude::*;
use reqwest;
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::env;

#[derive(Debug)]
pub struct GeminiClient {
    client: Client,
    api_keys: Vec<String>,
    current_key_index: usize,
    model: String,
    web_tools: WebTools,
    http_client: reqwest::Client,
}

// Structures for direct Gemini API function calling
#[derive(Debug, Clone, Serialize, Deserialize)]
struct GeminiRequest {
    contents: Vec<GeminiContent>,
    tools: Option<Vec<crate::tools::Tool>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct GeminiContent {
    role: String,
    parts: Vec<GeminiPart>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
enum GeminiPart {
    Text { text: String },
    FunctionCall { 
        #[serde(rename = "functionCall")]
        function_call: FunctionCall 
    },
    FunctionResponse { 
        #[serde(rename = "functionResponse")]
        function_response: crate::tools::FunctionResponse 
    },
}

#[derive(Debug, Serialize, Deserialize)]
struct GeminiResponse {
    candidates: Vec<GeminiCandidate>,
}

#[derive(Debug, Serialize, Deserialize)]
struct GeminiCandidate {
    content: GeminiContent,
}

impl GeminiClient {
    pub fn new(model: String, api_keys: Vec<String>) -> Result<Self> {
        if api_keys.is_empty() {
            return Err(anyhow::anyhow!("No API keys provided"));
        }

        // Validate API key formats
        for key in &api_keys {
            if !validate_api_key_format(key) {
                log_warn(&format!(
                    "API key format validation failed for key: {}",
                    key
                ));
                eprintln!("⚠️  Warning: API key format seems incorrect.");
                eprintln!("   Expected format: AIzaSy... (39 characters)");
            }
        }

        log_info(&format!(
            "Initializing Gemini API client with model: {} and {} API key(s)",
            model,
            api_keys.len()
        ));

        // Start with a random key
        let mut rng = rand::thread_rng();
        let current_key_index = (0..api_keys.len()).choose(&mut rng).unwrap_or(0);

        // Set the initial API key
        env::set_var("GEMINI_API_KEY", &api_keys[current_key_index]);

        let client = Client::default();

        Ok(Self {
            client,
            api_keys,
            current_key_index,
            model,
            web_tools: WebTools::new(),
            http_client: reqwest::Client::new(),
        })
    }

    async fn try_generate_content(&self, prompt: &str, api_key: &str) -> Result<String> {
        log_debug(&format!(
            "Sending request to Gemini API with prompt length: {}",
            prompt.len()
        ));

        // Update the API key in environment for this request
        env::set_var("GEMINI_API_KEY", api_key);

        // Create the chat request
        let chat_req = ChatRequest::new(vec![ChatMessage::user(prompt)]);

        // Send the request using genai
        let chat_res = self
            .client
            .exec_chat(&self.model, chat_req, None)
            .await
            .context("Failed to send request to Gemini API")?;

        // Extract the response text
        let generated_text = chat_res
            .content_text_as_str()
            .context("Failed to extract text from Gemini response")?;

        // Check if the generated text is empty or just whitespace
        if generated_text.trim().is_empty() {
            log_error("Generated text is empty");
            return Err(anyhow::anyhow!(
                "No content was generated by the AI. The response was empty or contained only whitespace."
            ));
        }

        log_info(&format!(
            "Received response from Gemini API, length: {}",
            generated_text.len()
        ));

        Ok(generated_text.to_string())
    }

    #[allow(dead_code)]
    async fn try_generate_content_with_images(
        &self,
        prompt: &str,
        image_paths: &[String],
        api_key: &str,
    ) -> Result<String> {
        log_debug(&format!(
            "Sending multimodal request to Gemini API with prompt length: {} and {} image(s)",
            prompt.len(),
            image_paths.len()
        ));

        // Update the API key in environment for this request
        env::set_var("GEMINI_API_KEY", api_key);

        // Create content parts starting with text
        let mut content_parts = vec![ContentPart::from_text(prompt)];

        // Add image parts
        for image_path in image_paths {
            log_debug(&format!("Adding image to request: {}", image_path));

            // Get MIME type for the image
            let path = std::path::Path::new(image_path);
            let mime_type = crate::image::get_mime_type(path)
                .with_context(|| format!("Failed to get MIME type for image: {}", image_path))?;

            // Read image as base64
            let base64_data = crate::image::read_image_as_base64(image_path)
                .with_context(|| format!("Failed to read image as base64: {}", image_path))?;

            // Use from_image_base64 instead of from_image_url
            content_parts.push(ContentPart::from_image_base64(mime_type, base64_data));
        }

        // Create the chat request with content parts
        let chat_req = ChatRequest::new(vec![ChatMessage::user(content_parts)]);

        // Send the request using genai
        let chat_res = self
            .client
            .exec_chat(&self.model, chat_req, None)
            .await
            .context("Failed to send multimodal request to Gemini API")?;

        // Extract the response text
        let generated_text = chat_res
            .content_text_as_str()
            .context("Failed to extract text from Gemini response")?;

        // Check if the generated text is empty or just whitespace
        if generated_text.trim().is_empty() {
            log_error("Generated text is empty");
            return Err(anyhow::anyhow!(
                "No content was generated by the AI. The response was empty or contained only whitespace."
            ));
        }

        log_info(&format!(
            "Received response from Gemini API, length: {}",
            generated_text.len()
        ));

        Ok(generated_text.to_string())
    }

    async fn try_generate_content_with_image_sources(
        &self,
        prompt: &str,
        image_sources: &[ImageSource],
        api_key: &str,
    ) -> Result<String> {
        log_debug(&format!(
            "Sending multimodal request to Gemini API with prompt length: {} and {} image source(s)",
            prompt.len(),
            image_sources.len()
        ));

        // Update the API key in environment for this request
        env::set_var("GEMINI_API_KEY", api_key);

        // Create content parts starting with text
        let mut content_parts = vec![ContentPart::from_text(prompt)];

        // Add image parts from various sources
        for image_source in image_sources {
            match image_source {
                ImageSource::File(image_path) => {
                    log_debug(&format!("Adding file image to request: {}", image_path));

                    // Get MIME type for the image
                    let path = std::path::Path::new(image_path);
                    let mime_type = crate::image::get_mime_type(path).with_context(|| {
                        format!("Failed to get MIME type for image: {}", image_path)
                    })?;

                    // Read image as base64
                    let base64_data =
                        crate::image::read_image_as_base64(image_path).with_context(|| {
                            format!("Failed to read image as base64: {}", image_path)
                        })?;

                    content_parts.push(ContentPart::from_image_base64(mime_type, base64_data));
                }
                ImageSource::Clipboard => {
                    log_debug("Adding clipboard image to request");

                    // Read image from clipboard
                    let image_data =
                        read_clipboard_image().context("Failed to read image from clipboard")?;

                    // Convert to PNG base64
                    let base64_data = convert_image_data_to_base64(&image_data)
                        .context("Failed to convert clipboard image to PNG base64")?;

                    // Use PNG MIME type for clipboard images
                    content_parts.push(ContentPart::from_image_base64(
                        "image/png".to_string(),
                        base64_data,
                    ));
                }
            }
        }

        // Create the chat request with content parts
        let chat_req = ChatRequest::new(vec![ChatMessage::user(content_parts)]);

        // Send the request using genai
        let chat_res = self
            .client
            .exec_chat(&self.model, chat_req, None)
            .await
            .context("Failed to send multimodal request to Gemini API")?;

        // Extract the response text
        let generated_text = chat_res
            .content_text_as_str()
            .context("Failed to extract text from Gemini response")?;

        // Check if the generated text is empty or just whitespace
        if generated_text.trim().is_empty() {
            log_error("Generated text is empty");
            return Err(anyhow::anyhow!(
                "No content was generated by the AI. The response was empty or contained only whitespace."
            ));
        }

        log_info(&format!(
            "Received response from Gemini API, length: {}",
            generated_text.len()
        ));

        Ok(generated_text.to_string())
    }

    async fn generate_content_with_tools(&mut self, prompt: &str) -> Result<String> {
        log_info("Using function calling mode with web tools");
        
        let api_key = &self.api_keys[self.current_key_index];
        
        // Check if the prompt might benefit from web tools
        let needs_web_access = self.should_use_web_tools(prompt);
        
        if !needs_web_access {
            log_debug("Prompt doesn't seem to need web access, using standard mode");
            return self.try_generate_content(prompt, api_key).await;
        }
        
        log_info("Prompt may benefit from web access, enabling tools");
        
        let tools = WebTools::create_tools();
        let mut conversation_history = vec![GeminiContent {
            role: "user".to_string(),
            parts: vec![GeminiPart::Text { text: prompt.to_string() }],
        }];
        
        // Function calling conversation loop
        for round in 0..3 { // Max 3 rounds to prevent infinite loops
            log_debug(&format!("Function calling round {}", round + 1));
            
            let request = GeminiRequest {
                contents: conversation_history.clone(),
                tools: Some(tools.clone()),
            };
            
            let response = self.call_gemini_api_with_tools(&request, api_key).await?;
            
            if let Some(candidate) = response.candidates.first() {
                let mut has_function_calls = false;
                let mut text_response = String::new();
                
                // Process the response parts
                for part in &candidate.content.parts {
                    match part {
                        GeminiPart::Text { text } => {
                            if !text.trim().is_empty() {
                                text_response.push_str(text);
                            }
                        }
                        GeminiPart::FunctionCall { function_call } => {
                            has_function_calls = true;
                            log_info(&format!("AI wants to call function: {}", function_call.name));
                            
                            // Execute the function call
                            match self.web_tools.execute_function_call(function_call).await {
                                Ok(function_response) => {
                                    log_info(&format!("Function {} executed successfully", function_call.name));
                                    
                                    // Add the function call to conversation history
                                    conversation_history.push(GeminiContent {
                                        role: "model".to_string(),
                                        parts: vec![GeminiPart::FunctionCall { function_call: function_call.clone() }],
                                    });
                                    
                                    // Add the function response to conversation history
                                    conversation_history.push(GeminiContent {
                                        role: "user".to_string(),
                                        parts: vec![GeminiPart::FunctionResponse { function_response }],
                                    });
                                }
                                Err(e) => {
                                    log_error(&format!("Function call failed: {}", e));
                                    // Add error response
                                    conversation_history.push(GeminiContent {
                                        role: "user".to_string(),
                                        parts: vec![GeminiPart::FunctionResponse { 
                                            function_response: crate::tools::FunctionResponse {
                                                name: function_call.name.clone(),
                                                response: json!({
                                                    "error": format!("Function call failed: {}", e)
                                                }),
                                            }
                                        }],
                                    });
                                }
                            }
                        }
                        GeminiPart::FunctionResponse { .. } => {
                            // This shouldn't happen in the response, but ignore it
                        }
                    }
                }
                
                // If no function calls, we have the final response
                if !has_function_calls {
                    if text_response.trim().is_empty() {
                        return Err(anyhow::anyhow!("Empty response from Gemini API"));
                    }
                    log_info(&format!("Function calling completed successfully, response length: {}", text_response.len()));
                    return Ok(text_response);
                }
                
                // If we have function calls but also text, add the text to conversation
                if !text_response.trim().is_empty() {
                    conversation_history.push(GeminiContent {
                        role: "model".to_string(),
                        parts: vec![GeminiPart::Text { text: text_response }],
                    });
                }
            } else {
                return Err(anyhow::anyhow!("No candidates in Gemini API response"));
            }
        }
        
        Err(anyhow::anyhow!("Function calling loop exceeded maximum rounds"))
    }
    
    async fn call_gemini_api_with_tools(&self, request: &GeminiRequest, api_key: &str) -> Result<GeminiResponse> {
        let url = format!(
            "https://generativelanguage.googleapis.com/v1beta/models/{}:generateContent?key={}",
            self.model, api_key
        );
        
        log_debug(&format!("Sending function calling request to: {}", url));
        
        let response = self
            .http_client
            .post(&url)
            .header("Content-Type", "application/json")
            .json(request)
            .send()
            .await
            .context("Failed to send request to Gemini API")?;
            
        if !response.status().is_success() {
            let status = response.status();
            let error_text = response.text().await.unwrap_or_else(|_| "Unknown error".to_string());
            return Err(anyhow::anyhow!("Gemini API error {}: {}", status, error_text));
        }
        
        let response_text = response
            .text()
            .await
            .context("Failed to get response text from Gemini API")?;
            
        log_debug(&format!("Raw Gemini API response: {}", response_text));
        
        let gemini_response: GeminiResponse = serde_json::from_str(&response_text)
            .context("Failed to parse Gemini API response JSON")?;
            
        Ok(gemini_response)
    }
    
    fn should_use_web_tools(&self, prompt: &str) -> bool {
        let prompt_lower = prompt.to_lowercase();
        
        // Keywords that suggest web search might be useful
        let search_indicators = [
            "latest", "recent", "current", "today", "news", "update", 
            "what's new", "find", "search", "look up", "information about",
            "tell me about", "2024", "2025", "this year", "happening now",
            "price", "cost", "stock", "weather", "events", "schedule"
        ];
        
        // Keywords that suggest URL reading might be useful
        let url_indicators = [
            "http://", "https://", "www.", ".com", ".org", ".net", ".io",
            "read this", "summarize", "content of", "page", "website",
            "article", "documentation", "docs"
        ];
        
        search_indicators.iter().any(|&indicator| prompt_lower.contains(indicator)) ||
        url_indicators.iter().any(|&indicator| prompt_lower.contains(indicator))
    }

    fn try_next_api_key(&mut self) -> Result<String> {
        if self.api_keys.len() <= 1 {
            return Err(anyhow::anyhow!("No alternative API keys available"));
        }

        // Find next available key (simple round-robin)
        self.current_key_index = (self.current_key_index + 1) % self.api_keys.len();
        Ok(self.api_keys[self.current_key_index].clone())
    }

    fn handle_auth_error(&self, error_text: &str) -> Result<String> {
        eprintln!();
        eprintln!("🔐 Authentication Error");
        eprintln!("========================");
        eprintln!();
        eprintln!("The Gemini API rejected your request due to authentication issues.");
        eprintln!();
        eprintln!("Common causes:");
        eprintln!("• Invalid API key");
        eprintln!("• API key doesn't have proper permissions");
        eprintln!("• API key is disabled or suspended");
        eprintln!("• Billing not enabled on your Google Cloud project");
        eprintln!();
        eprintln!("Error details: {}", error_text);
        eprintln!();
        eprintln!("To fix this:");
        eprintln!("1. Verify your API key at: {}", GEMINI_API_KEY_URL);
        eprintln!("2. Check billing is enabled: https://console.cloud.google.com/billing");
        eprintln!(
            "3. Ensure the Generative AI API is enabled: https://console.cloud.google.com/apis/"
        );
        eprintln!();

        // Ask if user wants to open the API key page
        eprintln!("Open API key page in browser? (y/N)");
        let mut input = String::new();
        if std::io::stdin().read_line(&mut input).is_ok() {
            let response = input.trim().to_lowercase();
            if response == "y" || response == "yes" {
                if let Err(e) = webbrowser::open(GEMINI_API_KEY_URL) {
                    log_error(&format!("Failed to open browser: {}", e));
                    eprintln!(
                        "Could not open browser. Please visit: {}",
                        GEMINI_API_KEY_URL
                    );
                } else {
                    log_info("Opened API key page in browser");
                }
            }
        }

        Err(anyhow::anyhow!(
            "Authentication failed. Please check your API key and billing settings."
        ))
    }
}

#[async_trait]
impl AiProvider for GeminiClient {
    async fn generate_content(&mut self, prompt: &str) -> Result<String> {
        // Try function calling first if it might be beneficial
        if self.should_use_web_tools(prompt) {
            log_info("Attempting to use function calling with web tools");
            match self.generate_content_with_tools(prompt).await {
                Ok(result) => return Ok(result),
                Err(e) => {
                    log_warn(&format!("Function calling failed, falling back to standard mode: {}", e));
                }
            }
        }

        // Fallback to standard genai implementation
        let current_key = self.api_keys[self.current_key_index].clone();

        // Try with current API key first
        match self.try_generate_content(prompt, &current_key).await {
            Ok(result) => Ok(result),
            Err(e) => {
                let error_string = e.to_string();

                // Check if it's a rate limit error and we can try another key
                if error_string.contains("429") || error_string.contains("Too Many Requests") {
                    log_info("Rate limit hit, trying to fallback to another API key");

                    match self.try_next_api_key() {
                        Ok(next_key) => {
                            log_info("Found alternative API key, retrying request");

                            match self.try_generate_content(prompt, &next_key).await {
                                Ok(result) => {
                                    log_info("Successfully used alternative API key");
                                    Ok(result)
                                }
                                Err(fallback_error) => {
                                    log_error("Alternative API key also failed");
                                    let fallback_error_string = fallback_error.to_string();
                                    if fallback_error_string.contains("429")
                                        || fallback_error_string.contains("Too Many Requests")
                                    {
                                        eprintln!(
                                            "⚠️  Rate limit exceeded on all available API keys."
                                        );
                                    }
                                    Err(fallback_error)
                                }
                            }
                        }
                        Err(_) => {
                            log_warn("No alternative API keys available for fallback");
                            eprintln!(
                                "⚠️  Rate limit exceeded and no alternative API keys available."
                            );
                            Err(e)
                        }
                    }
                } else {
                    // Check if it's an authentication error
                    if error_string.contains("401")
                        || error_string.contains("403")
                        || error_string.contains("authentication")
                        || error_string.contains("permission")
                    {
                        return self.handle_auth_error(&error_string);
                    }
                    Err(e)
                }
            }
        }
    }

    #[allow(dead_code)]
    async fn generate_content_with_images(
        &mut self,
        prompt: &str,
        image_paths: &[String],
    ) -> Result<String> {
        if image_paths.is_empty() {
            // No images, use regular text-only method
            return self.generate_content(prompt).await;
        }

        let current_key = self.api_keys[self.current_key_index].clone();

        // Try with current API key first
        match self
            .try_generate_content_with_images(prompt, image_paths, &current_key)
            .await
        {
            Ok(result) => Ok(result),
            Err(e) => {
                let error_string = e.to_string();

                // Check if it's a rate limit error and we can try another key
                if error_string.contains("429") || error_string.contains("Too Many Requests") {
                    log_info("Rate limit hit, trying to fallback to another API key");

                    match self.try_next_api_key() {
                        Ok(next_key) => {
                            log_info("Found alternative API key, retrying multimodal request");

                            match self
                                .try_generate_content_with_images(prompt, image_paths, &next_key)
                                .await
                            {
                                Ok(result) => {
                                    log_info("Successfully used alternative API key for multimodal request");
                                    Ok(result)
                                }
                                Err(fallback_error) => {
                                    log_error(
                                        "Alternative API key also failed for multimodal request",
                                    );
                                    let fallback_error_string = fallback_error.to_string();
                                    if fallback_error_string.contains("429")
                                        || fallback_error_string.contains("Too Many Requests")
                                    {
                                        eprintln!(
                                            "⚠️  Rate limit exceeded on all available API keys."
                                        );
                                    }
                                    Err(fallback_error)
                                }
                            }
                        }
                        Err(_) => {
                            log_warn("No alternative API keys available for fallback");
                            eprintln!(
                                "⚠️  Rate limit exceeded and no alternative API keys available."
                            );
                            Err(e)
                        }
                    }
                } else {
                    // Check if it's an authentication error
                    if error_string.contains("401")
                        || error_string.contains("403")
                        || error_string.contains("authentication")
                        || error_string.contains("permission")
                    {
                        return self.handle_auth_error(&error_string);
                    }
                    Err(e)
                }
            }
        }
    }

    async fn generate_content_with_image_sources(
        &mut self,
        prompt: &str,
        image_sources: &[ImageSource],
    ) -> Result<String> {
        if image_sources.is_empty() {
            // No images, use regular text-only method
            return self.generate_content(prompt).await;
        }

        let current_key = self.api_keys[self.current_key_index].clone();

        // Try with current API key first
        match self
            .try_generate_content_with_image_sources(prompt, image_sources, &current_key)
            .await
        {
            Ok(result) => Ok(result),
            Err(e) => {
                let error_string = e.to_string();

                // Check if it's a rate limit error and we can try another key
                if error_string.contains("429") || error_string.contains("Too Many Requests") {
                    log_info("Rate limit hit, trying to fallback to another API key");

                    match self.try_next_api_key() {
                        Ok(next_key) => {
                            log_info("Found alternative API key, retrying multimodal request with image sources");

                            match self
                                .try_generate_content_with_image_sources(
                                    prompt,
                                    image_sources,
                                    &next_key,
                                )
                                .await
                            {
                                Ok(result) => {
                                    log_info("Successfully used alternative API key for multimodal request with image sources");
                                    Ok(result)
                                }
                                Err(fallback_error) => {
                                    log_error(
                                        "Alternative API key also failed for multimodal request with image sources",
                                    );
                                    let fallback_error_string = fallback_error.to_string();
                                    if fallback_error_string.contains("429")
                                        || fallback_error_string.contains("Too Many Requests")
                                    {
                                        eprintln!(
                                            "⚠️  Rate limit exceeded on all available API keys."
                                        );
                                    }
                                    Err(fallback_error)
                                }
                            }
                        }
                        Err(_) => {
                            log_warn("No alternative API keys available for fallback");
                            eprintln!(
                                "⚠️  Rate limit exceeded and no alternative API keys available."
                            );
                            Err(e)
                        }
                    }
                } else {
                    // Check if it's an authentication error
                    if error_string.contains("401")
                        || error_string.contains("403")
                        || error_string.contains("authentication")
                        || error_string.contains("permission")
                    {
                        return self.handle_auth_error(&error_string);
                    }
                    Err(e)
                }
            }
        }
    }

    fn model_name(&self) -> &str {
        &self.model
    }

    fn provider_name(&self) -> &str {
        "Gemini"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_gemini_client_creation() {
        let test_keys = vec![
            "AIzaSyKey1ForTesting123456789012345".to_string(),
            "AIzaSyKey2ForTesting123456789012345".to_string(),
        ];
        let model = "gemini-2.5-flash-lite".to_string();

        let client = GeminiClient::new(model.clone(), test_keys.clone());
        assert!(client.is_ok());

        let client = client.unwrap();
        assert_eq!(client.model_name(), &model);
        assert_eq!(client.provider_name(), "Gemini");
        assert_eq!(client.api_keys.len(), 2);
    }

    #[tokio::test]
    async fn test_gemini_client_empty_keys() {
        let empty_keys = vec![];
        let model = "gemini-2.5-flash-lite".to_string();

        let result = GeminiClient::new(model, empty_keys);
        assert!(result.is_err());
    }
}
